feat(connectivity): Check rds cfg domains for pod-to-url
openservicemesh/osm-health pull request #65
Opened 2021-08-16 16:11 UTC by johnsonshi

Depends on functionality implemented in #64.

Signed-off-by: Johnson Shi <Johnson.Shi@microsoft.com>

2021-08-16 16:11 UTC, johnsonshi commented
Depends on #64.

2021-08-16 22:08 UTC, SanyaKochhar approved these changes

2021-08-16 22:30 UTC, draychev requested changes
I see that this PR is for `pod-to-url`, but the changes are to the `pkg/connectivity/pod-to-pod.go` file.

It seems to me that the changes should be in `pkg/connectivity/pod-to-url.go` around here:
https://github.com/openservicemesh/osm-health/blob/dde34257d45b321508553186b25ed4409798dc87/pkg/connectivity/pod-to-url.go#L14


The way I was thinking about this - if you did some pod to `http://bookstore.bookstore/buy-a-book`:
  1. we'll resolve a bunch of pods for `bookstore.bookstore` and run the existing `pod-to-pod` for each pod discovered
  2. we'll check routes for each pod in #1 for the route provided via the CLI - `/buy-new-book`

2021-08-19 15:40 UTC, johnsonshi commented on pkg/connectivity/pod-to-pod.go
> +		envoy.HasInboundDynamicRouteConfigDomainPodCheck(dstConfigGetter, fromPod),
@draychev - This is just renaming the method names - the bulk of this PR lies in pod-to-url.

2021-08-19 15:59 UTC, draychev approved these changes

2021-08-19 16:00 UTC, draychev commented
Happy to take a different approach - perhaps let's make this work, then dedupe and reorganize the code base.

2021-08-19 21:36 UTC, merged