check(controller): Check controller http server health probes.
openservicemesh/osm-health pull request #98
Opened 2021-09-13 12:40 UTC by johnsonshi

check(controller): Check controller http server health probes.

Checks controller http server health probes for
the health of the osm-controller pods.

Signed-off-by: Johnson Shi <Johnson.Shi@microsoft.com>

2021-09-14 16:28 UTC, johnsonshi commented
@SanyaKochhar // @draychev // @jaellio - Should we add some checks of `/metrics` from osm-controller's http server as well? I see lots of potentially useful metrics that we can obtain from `/metrics`. Example: https://pastebin.com/B06MeZwY

2021-09-17 16:49 UTC, draychev requested changes
@johnsonshi I recommend we only check the response headers and status code - this should be sufficient.
I don't think we should be checking the response body and matching against specific text. All we care about is response code `200` and potentially some interesting headers.

2021-09-17 16:49 UTC, draychev commented on pkg/osm/osm_controller_http_server.go
> +	return nil
Checking the response code (should be `200`) is sufficient.
We certainly should not be checking the response body. Response body should mostly be for humans to understand things went ok. Machines should be checking the response codes and headers in this particular scenario.

2021-09-20 07:53 UTC, johnsonshi commented on pkg/osm/controller/types.go
> +var log = logger.New("control-plane/osm-controller/http-server")
@draychev is this a suitable log name?

2021-09-21 22:14 UTC, draychev approved these changes

2021-09-21 22:15 UTC, merged